networks:
  team07:
    external: true

services:
  tokengram-backend:
    build: .
    container_name: tokengram-backend
    image: tokengram-backend
    restart: unless-stopped
    ports:
      - ${TOKENGRAM_BACKEND_HOST_PORT:-5000}:5000
    networks:
      - team07
    volumes:
      - tokengram-backend_keys:/etc/team07/tokengram/backend/data-protection-keys
      - ../storage/uploads/public:/var/tokengram/uploads/public
      - ./appsettings.json:/app/appsettings.json:ro

volumes:
  tokengram-backend_keys:
    name: tokengram-backend_keys
